# Copy this to Streamlit Cloud → Settings → Secrets
# Then replace with your actual Stripe keys

# Stripe Configuration
STRIPE_PUBLISHABLE_KEY = "pk_test_YOUR_KEY_HERE"
STRIPE_SECRET_KEY = "sk_test_YOUR_KEY_HERE"

# Price IDs (create products in Stripe dashboard first)
BASIC_PRICE_ID = "price_YOUR_BASIC_PRICE_ID"
PRO_PRICE_ID = "price_YOUR_PRO_PRICE_ID"

# Optional: Webhook secret (from Stripe → Developers → Webhooks)
STRIPE_WEBHOOK_SECRET = "whsec_YOUR_WEBHOOK_SECRET"
